#+TITLE:   Git
#+AUTHOR:  Chris Zheng
#+EMAIL:   z@caudate.me
#+OPTIONS: toc:nil 
#+STARTUP: showall

* Bfg

The [[https://rtyley.github.io/bfg-repo-cleaner][BFG]] is a simpler, faster alternative to git-filter-branch for
cleansing bad data out of your Git repository history:

- Removing Crazy Big Files 
- Removing Passwords, Credentials & other Private data
 
The ~git-filter-branch~ command is enormously powerful and can do
things that the BFG can't - but the BFG is much better for the tasks
above, because:

- ~Faster~ : 10 - 720x faster
- ~Simpler~ : The BFG isn't particularily clever, but is focused on
  making the above tasks easy
- ~Beautiful~ : If you need to, you can use the beautiful Scala language
  to customise the BFG. Which has got to be better than Bash scripting
  at least some of the time.

** Install

#+DESC: From https://rtyley.github.io/bfg-repo-cleaner/
#+BEGIN_SRC bash :cache no :eval no
wget -O ~/bin/bfg-1.13.1.jar https://repo1.maven.org/maven2/com/madgag/bfg/1.13.1/bfg-1.13.1.jar
echo "alias bfg=\"java -var $HOME/bin/bfg-1.13.1.jar\"" >> ~/.bash_custom
source ~/.bash_custom
#+END_SRC

** Examples

In all these examples bfg is an alias for java -jar bfg.jar.

#+DESC: Delete all files named 'id_rsa' or 'id_dsa'
#+BEGIN_SRC bash :cache no :eval no
bfg --delete-files id_{dsa,rsa} my-repo.git
#+END_SRC

#+DESC: Remove all blobs bigger than 50 megabytes
#+BEGIN_SRC bash :cache no :eval no
bfg --strip-blobs-bigger-than 50M my-repo.git
#+END_SRC


#+DESC: Replace all passwords listed in a file
#+BEGIN_SRC bash :cache no :eval no
bfg --replace-text passwords.txt  my-repo.git
#+END_SRC

#+DESC: Remove all folders or files named '.git' - a reserved filename in Git.
#+BEGIN_SRC bash :cache no :eval no
bfg --delete-folders .git --delete-files .git  --no-blob-protection  my-repo.git
#+END_SRC

** Links

- [[https://github.com/rtyley/bfg-repo-cleaner][GitHub - rtyley/bfg-repo-cleaner]]
- [[https://www.theguardian.com/info/developer-blog/2013/apr/29/rewrite-git-history-with-the-bfg][Fast & simple Git history rewrites with The BFG]]
