(require 'etude-core-code)
(require 'etude-core-git)
(require 'etude-core-global)
(require 'etude-core-lisp)
(require 'etude-core-management)
(require 'etude-core-shell)
(require 'etude-core-style)
(require 'etude-core-util)
(require 'etude-core-bindings)

;;(require 'etude-mode-info)
;;(require 'etude-mode-dired)
;;(require 'etude-mode-ivy)

(provide 'etude-core)
